InvoicesApp/Controllers/ErrorViewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace InvoicesApp.Controllers
{
    [Route("~/error/statuscode")]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorViewController : Controller
    {
        private readonly ILogger<ErrorViewController> _logger;

        public ErrorViewController(ILogger<ErrorViewController> logger)
        {
            _logger = logger;
        }

        [Route("403")]
        public IActionResult Error403()
        {
            //   return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            return View();
        }

        [Route("404")]
        public IActionResult Error404()
        {
            return View();
        }

        [Route("500")]
        public IActionResult Error500()
        {
            return View();
        }
    }
}

InvoicesApp/Controllers/HomeViewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace InvoicesApp.Controllers
{
    [Route("~/")]
    public class HomeViewController : Controller
    {
        private readonly ILogger<HomeViewController> _logger;

        public HomeViewController(ILogger<HomeViewController> logger)
        {
            _logger = logger;
        }


        public IActionResult List()
        {
            return View();
        }

        [Route("create/contactdata")]
        public IActionResult CreateContact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("create/assignment")]
        public IActionResult CreateAssignments()
        {
            return View();
        }

        [Route("settings")]
        public IActionResult InvoicesSettings()
        {
            return View();
        }

        [Route("invoice/details")]
        public IActionResult Details()
        {
            return View();
        }
    }
}

InvoicesApp/Views/ErrorView/Error403.cshtml
@{
    Layout = "Error";
}
<div class="error-area ptb--100 text-center">
    <div class="container">
        <div class="error-content">
            <h2>403</h2>
            <p>Access to this resource on the server is denied</p>
            <a onclick="location.href = '@Url.Action(" List","HomeView")';">Back to Dashboard</a>
        </div>
    </div>
</div>

InvoicesApp/Views/ErrorView/Error404.cshtml
@{
    Layout = "Error";
}
<div class="error-area ptb--100 text-center">
    <div class="container">
        <div class="error-content">
            <h2>404</h2>
            <p>Ooops! Something went wrong .</p>
            <a onclick="location.href = '@Url.Action(" List","HomeView")';">Back to Dashboard</a>
        </div>
    </div>
</div>

InvoicesApp/Views/ErrorView/Error500.cshtml
@{
    Layout = "Error";
}
<div class="error-area ptb--100 text-center">
    <div class="container">
        <div class="error-content">
            <h2>500</h2>
            <p>Internal Server Error!</p>
            <a onclick="location.href = '@Url.Action("List","HomeView")';">Back to Dashboard</a>
        </div>
    </div>
</div>